// File generated by Antigravity placeholder. Overwritten by flutterfire configure.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgUWNRx876IcXu6079yMCB8BJ9lCOZr0',
    appId: '1:619239393964:android:09a118355ecd83405a6d09',
    messagingSenderId: '619239393964',
    projectId: 'soulsync-85121',
    storageBucket: 'soulsync-85121.firebasestorage.app',
  );
}
